### ISSUE TITLE
Suggestion on snap package

### ISSUE THREAD

**Issue by soumyaDghosh** [andreibachim/shortcut#8]
Hii, I saw your request for personal files in the store. You can request the developers to allow the snap to be installed without auto connection. And then you can add the instructions in your readme and the store description page about how to install this snap.

**Comment by andreibachim** [comment]
That was also my first idea, but the request got rejected and I was sent to ask for auto-connections.

I do not currently plan to release the app to Snap store anymore. Might revisit the idea in the future.
